<a href="https://colab.research.google.com/github/brandoncohen23/Probability_Statistics-1/blob/main/Lab_3_Cohen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Lab Notebook #3

### Loops

In [151]:
for i in range(10): # creates a range for i up from 0-9 (10 values)
    print(i)

0
1
2
3
4
5
6
7
8
9


In [152]:
for i in range(5,8): # range for i from 5-7
    print(i)

5
6
7


In [153]:
for i in range(3): # inserts "Test Number:" in front of each value in range
    print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [154]:
def square(x): # defines code to square the x value
    return x**2

In [155]:
square(5) # square of 5

25

In [156]:
square(6) # square of 6

36

In [157]:
square(123456) # square of 123456

15241383936

In [158]:
square(square(2)) # square of the square of 2

16

In [159]:
square(square(5)) # square of the square of 5

625

In [160]:
square(square(square(2))) # the square of the square of square of 2

256

In [161]:
def add_two(x): # defines the command to add two for the x value
    return x+2

In [162]:
add_two(5) # adding 2 to 5

7

In [163]:
square(add_two(5)) # the square root of adding 2 to 5

49

### Logical Branching

In [164]:
choice = "apple" # defining a choice to be apple

In [165]:
if choice == "apple": # sets that if you choose apple then the program will state that you chose apples

    print("You choose apples.")

else:


    print("You did not choose apples.") # if you don't choose apple then it state that you did not choose apples

You choose apples.


In [166]:
choice = "orange" # sets the choice as orange

In [167]:
if choice == "apple": # defines that it will state that you choose either option

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123) 

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:

    print("You did not choose apples or oranges.") # defines that if you don't choose neither than it will say so
    print("Thank you, shop again!")

You choose oranges.
Thank you, shop again!


### User Input

In [168]:
choice = input("Please enter your choice (i.e. apple):") # assigns an input to choose which allows you to make your choice

Please enter your choice (i.e. apple):apple


In [169]:
choice # tells you your choice

'apple'

In [170]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") # gives you a statement depending on what you chose

You choose apples.


### Coins

sets up the coin flip

In [171]:
np.random.random()

0.49197563437751457

In [172]:
np.random.random() > 0.5

False

In [173]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [174]:
flip_coin()

Tails


### Graphic Output

creates the coin flip similar to lab 2

In [175]:
from IPython.core.display import display, HTML

In [176]:
display(HTML('<h1>Hello, world!</h1>'))

In [177]:
def coin(): # defines coin to generate a random number between 0-1
  return np.random.randint(2)

In [178]:
coin()

0

In [179]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) # displays front of quarter

In [180]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' # the picture links of heads and tails
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [181]:
def show_img(img): # defines code to show the image
  display(HTML('<img src=' + img + '>'))

In [182]:
show_img(heads) # shows heads

In [183]:
show_img(tails) # shows tails

In [184]:
def flip_coin(): # defines code to flip coin and give result

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [185]:
flip_coin() # resulted in heads

In [186]:
for i in range(5): # gives five results
    flip_coin()

In [187]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Speed Test

In [188]:
def shuffle(x): # creates a shuffle 
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [189]:
a = np.arange(52) # sets a range from 0-51

In [190]:
shuffle(a) # shows the shuffled array

array([45, 22,  1, 29, 24, 46, 18, 51, 16, 17, 49, 11, 47, 32,  6, 25, 42,
       31, 40, 20, 44, 27, 48, 19,  0, 15, 26,  8, 14, 35, 43, 34, 12, 28,
        7, 50, 36, 39, 21, 38,  2, 23, 41, 10, 33, 37,  5,  3, 13, 30,  4,
        9])

In [191]:
np.random.permutation(52) # randomizes the values

array([ 7, 25, 28, 27, 19, 44, 45,  2, 32, 39,  9, 31, 13,  3,  6, 17,  8,
       36, 29, 46, 41, 47, 15, 24, 30, 50, 11, 20,  0, 23,  4, 22, 18, 38,
       10, 26, 12, 16, 49,  5, 34, 51, 37, 48, 42, 14, 33, 40, 35, 21,  1,
       43])

In [192]:
%%timeit # times the shuffle
shuffle(a)

175 µs ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [193]:
%%timeit # times the permutation
np.random.permutation(52)

3.44 µs ± 285 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Cards

In [194]:
import numpy as np # imports the numpy program to help make the card shuffle

In [195]:
np.random.permutation(52) # random permutation values between 1-51

array([17, 33,  8,  2, 24, 46, 49, 38, 27, 47, 44, 31, 23, 10,  5,  6, 11,
       32,  0, 22, 37, 12, 35, 25, 28, 40, 21, 45,  1, 48, 15,  3,  9, 26,
       34, 19,  7, 16, 30, 18,  4, 39, 29, 36, 42, 51, 13, 20, 50, 14, 43,
       41])

In [196]:
cards = np.random.permutation(52) # defines the cards as these permutation values

In [197]:
cards # shows the array of randomized permutation values

array([11, 46, 30, 36, 21, 44,  3,  1, 32, 51, 29, 38, 13,  8,  7, 34, 26,
       39, 15, 19,  4, 35, 16,  5, 23, 25,  2, 50, 18,  6, 42,  9, 20, 17,
       27, 24, 47, 10, 33, 49, 41, 22, 28, 45, 43, 48, 12,  0, 40, 37, 31,
       14])

In [198]:
cards[0] # tells you what card is where

11

In [199]:
cards[1]

46

In [200]:
cards[2]

30

In [201]:
cards[10]

29

In [202]:
# inserts pngs of all the cards in the deck

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>


In [203]:
np.arange(52).reshape(4,13) # rearranges the array to 4 rows and 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [204]:
np.arange(52).reshape(4,13)%13 # makes the values for each row go from 0-12 (13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [205]:
np.arange(52).reshape(4,13)//13 # makes each row of 13 values replicate starting with 0 in the first row and ending with 3 in the last row

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [206]:
suits = ['Clubs','Spades','Hearts','Diamonds'] # defines suits with each of the card suits
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] # defines the names as the type of card

In [207]:
suits # shows the card suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [208]:
suits[0] # tells you what suit each card is

'Clubs'

In [209]:
names[1] # gives you what type of card (card number or king, queen, jack)

'Two'

In [210]:
def card_name(card_number): # defines the code to give you the suit and name of the card altogether

    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [211]:
card_name(0) # shows you the exact card it is in the deck

'Ace of Clubs'

In [212]:
card_name(51)

'King of Diamonds'

In [213]:
card_name(17)

'Five of Spades'

In [214]:
cards = np.random.permutation(52) # randomizes the deck

In [215]:
top_of_deck         = card_name(cards[0]) # defines card locations as code
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [216]:
top_of_deck,second_card_in_deck,last_card_in_deck # gives you the exact cards in those locations in the deck

('Queen of Clubs', 'Nine of Diamonds', 'Seven of Spades')

In [217]:
for i in range(5): # gives a range of the first 5 cards in the deck
    print(card_name(cards[i]))

Queen of Clubs
Nine of Diamonds
Five of Clubs
Nine of Clubs
Three of Spades


In [228]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" # card image links
card_url_tail = ".png"

In [219]:
suit = ['k','p','s','l'] # define suits as single letters
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] # defines cards as actual numbers and single letters for king, queen, jack

In [220]:
i = np.random.randint(4) # sets up values using your arrangement from earlier 
j = np.random.randint(13)

In [221]:
i,j # shows the suit and card as just x and y values

(2, 4)

In [222]:
suit[i] # gives you the suit single letter

's'

In [223]:
card[j]  # gives you the exact card

'5'

In [224]:
from IPython.core.display import display, HTML

In [225]:
def show_img(img): # defines the code to show the card image
    display(HTML('<img src=' + img + '>'))

In [226]:
img = card_url_head + suit[i] + card[j] + card_url_tail # putting this all together gives the exact card as a picture

In [227]:
show_img(img) # shows you the exact card in the deck